source:
  path: "data/"

bronze:
  path: "datamart/bronze/"
  tables:
    feature_clickstream:
      table_dir: feature_clickstream_raw
      partition_col: snapshot_date
    features_attributes:
      table_dir: features_attributes_raw
      partition_col: snapshot_date
    features_financials:
      table_dir: features_financials_raw
      partition_col: snapshot_date
    lms_loan_daily:
      table_dir: lms_loan_daily_raw
      partition_col: snapshot_date

silver:
  path: "datamart/silver/"
  tables:
    feature_clickstream:
      table_dir: feature_clickstream_cleaned
      source_dir: feature_clickstream_raw
      partition_col: snapshot_date
      columns:
        Customer_ID:
          type: string
          primary_key: true
        snapshot_date:
          type: date
          primary_key: true
        fe_1:
          type: float
        fe_2:
          type: float
        fe_3:
          type: float
        fe_4:
          type: float
        fe_5:
          type: float
        fe_6:
          type: float
        fe_7:
          type: float
        fe_8:
          type: float
        fe_9:
          type: float
        fe_10:
          type: float
        fe_11:
          type: float
        fe_12:
          type: float
        fe_13:
          type: float
        fe_14:
          type: float
        fe_15:
          type: float
        fe_16:
          type: float
        fe_17:
          type: float
        fe_18:
          type: float
        fe_19:
          type: float
        fe_20:
          type: float
    features_attributes:
      table_dir: features_attributes_cleaned
      source_dir: features_attributes_raw
      partition_col: snapshot_date
      columns:
        Customer_ID:
          type: string
          primary_key: true
        snapshot_date:
          type: date
          primary_key: true
        Name:
          type: string
        Age:
          type: integer
        SSN:
          type: string
        Occupation:
          type: string
    features_financials:
      table_dir: features_financials_cleaned
      source_dir: features_financials_raw
      partition_col: snapshot_date
      columns:
        Customer_ID:
          type: string
          primary_key: true
        snapshot_date:
          type: date
          primary_key: true
        Annual_Income:
          type: float
        Monthly_Inhand_Salary:
          type: float
        Num_Bank_Accounts:
          type: integer
        Num_Credit_Card:
          type: integer
        Interest_Rate:
          type: float
        Num_of_Loan:
          type: integer
        Type_of_Loan:
          type: string
        Delay_from_due_date:
          type: integer
        Num_of_Delayed_Payment:
          type: integer
        Changed_Credit_Limit:
          type: float
        Num_Credit_Inquiries:
          type: integer
        Credit_Mix:
          type: string
        Outstanding_Debt:
          type: float
        Credit_Utilization_Ratio:
          type: float
        Credit_History_Age:
          type: string
        Payment_of_Min_Amount:
          type: string
        Total_EMI_per_month:
          type: float
        Amount_invested_monthly:
          type: float
        Payment_Behaviour:
          type: string
        Monthly_Balance:
          type: float
    lms_loan_daily:
      table_dir: lms_loan_daily_cleaned
      source_dir: lms_loan_daily_raw
      partition_col: snapshot_date
      columns:
        loan_id:
          type: string
          primary_key: true
        snapshot_date:
          type: date
          primary_key: true
        Customer_ID:
          type: string
        loan_start_date:
          type: date
        tenure:
          type: integer
        installment_num:
          type: integer
        loan_amt:
          type: float
        due_amt:
          type: float
        paid_amt:
          type: float
        overdue_amt:
          type: float
        balance:
          type: float

gold:
  path: "datamart/gold/"
  tables:
    label_store:
      silver_source: lms_loan_daily_cleaned
      partition_col: snapshot_date
      columns:
        loan_id:
          type: string
        Customer_ID:
          type: string
        label:
          type: integer
        label_def:
          type: string
        snapshot_date:
          type: date
    feature_store:
      silver_sources:
        attributes: features_attributes_cleaned
        financials: features_financials_cleaned
        clickstream: feature_clickstream_cleaned
      partition_col: snapshot_date
      columns:
        Customer_ID:
          type: string
        snapshot_date:
          type: date
        Annual_Income:
          type: float
        Monthly_Inhand_Salary:
          type: float
        Num_Bank_Accounts:
          type: integer
        Num_Credit_Card:
          type: integer
        Interest_Rate:
          type: float
        Num_of_Loan:
          type: integer
        Type_of_Loan:
          type: string
        Delay_from_due_date:
          type: integer
        Num_of_Delayed_Payment:
          type: integer
        Changed_Credit_Limit:
          type: float
        Num_Credit_Inquiries:
          type: integer
        Outstanding_Debt:
          type: float
        Credit_Utilization_Ratio:
          type: float
        Total_EMI_per_month:
          type: float
        Amount_invested_monthly:
          type: float
        Monthly_Balance:
          type: float
        credit_history_months:
          type: integer
        credit_mix_encoded:
          type: integer
        payment_of_min_amount_encoded:
          type: integer
        pb_spend_level:
          type: integer
        pb_payment_value_level:
          type: integer
        debt_to_income_ratio:
          type: float
        emi_to_income_ratio:
          type: float
        Age:
          type: integer
        Occupation:
          type: string
        age_group:
          type: integer
        fe_1:
          type: float
        fe_2:
          type: float
        fe_3:
          type: float
        fe_4:
          type: float
        fe_5:
          type: float
        fe_6:
          type: float
        fe_7:
          type: float
        fe_8:
          type: float
        fe_9:
          type: float
        fe_10:
          type: float
        fe_11:
          type: float
        fe_12:
          type: float
        fe_13:
          type: float
        fe_14:
          type: float
        fe_15:
          type: float
        fe_16:
          type: float
        fe_17:
          type: float
        fe_18:
          type: float
        fe_19:
          type: float
        fe_20:
          type: float
        fe_sum:
          type: float
        fe_mean:
          type: float
        fe_1_mean:
          type: float
        fe_2_mean:
          type: float
        fe_3_mean:
          type: float
        fe_4_mean:
          type: float
        fe_5_mean:
          type: float
        fe_6_mean:
          type: float
        fe_7_mean:
          type: float
        fe_8_mean:
          type: float
        fe_9_mean:
          type: float
        fe_10_mean:
          type: float
        fe_11_mean:
          type: float
        fe_12_mean:
          type: float
        fe_13_mean:
          type: float
        fe_14_mean:
          type: float
        fe_15_mean:
          type: float
        fe_16_mean:
          type: float
        fe_17_mean:
          type: float
        fe_18_mean:
          type: float
        fe_19_mean:
          type: float
        fe_20_mean:
          type: float
        fe_1_std:
          type: float
        fe_2_std:
          type: float
        fe_3_std:
          type: float
        fe_4_std:
          type: float
        fe_5_std:
          type: float
        fe_6_std:
          type: float
        fe_7_std:
          type: float
        fe_8_std:
          type: float
        fe_9_std:
          type: float
        fe_10_std:
          type: float
        fe_11_std:
          type: float
        fe_12_std:
          type: float
        fe_13_std:
          type: float
        fe_14_std:
          type: float
        fe_15_std:
          type: float
        fe_16_std:
          type: float
        fe_17_std:
          type: float
        fe_18_std:
          type: float
        fe_19_std:
          type: float
        fe_20_std:
          type: float
